export const GET_CARS = "GET_CARS";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_ERROR = "EDIT_CAR_ERROR";
export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS";
export const CREATE_CAR_ERROR = "CREATE_CAR_ERROR";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR";