export const GET_DRUGS = "GET_DRUGS";
export const EDIT_DRUG_SUCCESS = "EDIT_DRUG_SUCCESS";
export const EDIT_DRUG_ERROR = "EDIT_DRUG_ERROR";
export const CREATE_DRUG_SUCCESS = "CREATE_DRUG_SUCCESS";
export const CREATE_DRUG_ERROR = "CREATE_DRUG_ERROR";
export const DELETE_DRUG_SUCCESS = "DELETE_DRUG_SUCCESS";
export const DELETE_DRUG_ERROR = "DELETE_DRUG_ERROR";