export const GET_PHARMACIES = "GET_PHARMACIES";
export const CREATE_PHARMACY_SUCCESS = "CREATE_PHARMACY_SUCCESS";
export const CREATE_PHARMACY_ERROR = "CREATE_PHARMACY_ERROR";
export const EDIT_PHARMACY_SUCCESS = "EDIT_PHARMACY_SUCCESS";
export const EDIT_PHARMACY_ERROR = "EDIT_PHARMACY_ERROR";
export const DELETE_PHARMACY_SUCCESS = "DELETE_PHARMACY_SUCCESS";
export const DELETE_PHARMACY_ERROR = "DELETE_PHARMACY_ERROR";